### PR TITLE
Change names of projectnames, Adapter and namespace

### LINKED ISSUE #163: Update Adapter Name to RFEM5
As we now have a RFEM 6 Toolkit this one should be renamed to RFEM5 to clarify which version this is intended for.
#### Suggestions to restore compliance:

See Above

### PR DESCRIPTION
**Pull request by Arne-Martensen**
### Issues addressed by this PR

Since there are two RFEM related toolkits available it was/is necessary to have a clear naming of both Tookits. Because of that the names of the pjojects, Adapter and namespaces within this RFEM_Toolkit needed to be changed, to make it clear to potatial users which Toolkit is required when.  

 Closes #163 

 

 ### Test files

 ### Changelog

- Projectname changed accordingly
- namspaces names changed accordingly
- Adapter name changed accordingly

 ### Additional comments

### CODE REVIEW

**Review by FraserGreenroyd — COMMENTED** [review]
@Arne-Martensen you probably already know but you'll need versioning for these changes.

I am happy to dispensate any code or documentation compliance issues that may be flagged by you touching every file to update the namespace if the bot does find any - but also happy if you want to fix them and bring the toolkit up to a high standard of compliance!

**Comment by Arne-Martensen** [comment]
@BHoMBot check versioning

**Comment by Arne-Martensen** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Review by staintono — APPROVED** [review]
Toolkit works as expected, no errors to the functionality of the toolkit. This was tested by pushing and pulling multiple elements such as bars and surfaces and all functioned as expected. The code was not reviewed.

**Comment by Arne-Martensen** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
