### PR TITLE
Remove PreviousVersion attributes for previous milestones

### PR DESCRIPTION
**Pull request by BHoMBot**
Remove PreviousVersion attributes for previous milestones

### CODE REVIEW

**Review by FraserGreenroyd — APPROVED** [review]
Reviewed from a CI/CD perspective. This meets the requirements of the removal. Final approval to be given by discipline for merge.

**Review by IsakNaslundBh — APPROVED** [review]
Looks fine to me. @MartinHenriksen could you confirm?

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check compliance
@BHoMBot check serialisation
@BHoMBot check null-handling
@BHoMBot check installer
@BHoMBot check versioning
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 3113203234

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 3113202219

**Pull request merged**
