### PR TITLE
Aligning with changes to AdapterIds

### LINKED ISSUE #100: Remove use of CustomData in the code
The files listed below have been detected as having code using `CustomData`. This detection has been automatic, and may have picked up on code comments or documentation. Please review each file carefully and remove all instances of `CustomData`.

This should be completed by the 30th October 2020.

<details>
<summary>Full list</summary>
<p>

 - [ ] RFEM_Toolkit\RFEM_Adapter\Convert\FromRFEM\Bar.cs

 - [ ] RFEM_Toolkit\RFEM_Adapter\Convert\FromRFEM\Constraint.cs

 - [ ] RFEM_Toolkit\RFEM_Adapter\Convert\FromRFEM\Material.cs

 - [ ] RFEM_Toolkit\RFEM_Adapter\Convert\FromRFEM\Node.cs

 - [ ] RFEM_Toolkit\RFEM_Adapter\Convert\FromRFEM\Panel.cs

 - [ ] RFEM_Toolkit\RFEM_Adapter\Convert\FromRFEM\SectionProperty.cs

 - [ ] RFEM_Toolkit\RFEM_Adapter\Convert\FromRFEM\SurfaceProperty.cs

 - [ ] RFEM_Toolkit\RFEM_Adapter\Convert\ToRFEM\Bar.cs

 - [ ] RFEM_Toolkit\RFEM_Adapter\Convert\ToRFEM\Panel.cs

 - [ ] RFEM_Toolkit\RFEM_Adapter\CRUD\Create\Bar.cs

 - [ ] RFEM_Toolkit\RFEM_Adapter\CRUD\Create\Edge.cs

 - [ ] RFEM_Toolkit\RFEM_Adapter\CRUD\Create\Material.cs

 - [ ] RFEM_Toolkit\RFEM_Adapter\CRUD\Create\Node.cs

 - [ ] RFEM_Toolkit\RFEM_Adapter\CRUD\Create\Panel.cs

 - [ ] RFEM_Toolkit\RFEM_Adapter\CRUD\Create\SectionProperty.cs

 - [ ] RFEM_Toolkit\RFEM_Adapter\CRUD\Create\SurfaceProperty.cs

</p>
</details>

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### NOTE: Depends on 

https://github.com/BHoM/BHoM/pull/1033
https://github.com/BHoM/BHoM_Engine/pull/2106
https://github.com/BHoM/BHoM_Adapter/pull/263

 ### Issues addressed by this PR

Aligning with changes in https://github.com/BHoM/BHoM/issues/1012

 

- Adding new RFEMId fragment
- Re-pointing all adapter ID assignments to this new fragment

 ### Test files

 ### Changelog

 ### Additional comments

EDIT: Fixes #100

### CODE REVIEW

**Review by MartinHenriksen — APPROVED** [review]
LGTM 👍

**Comment by MartinHenriksen** [comment]
Edited PR to close issue #100

**Comment by IsakNaslundBh** [comment]
> Edited PR to close issue #100

Thanks @MartinHenriksen . Did not close as I was not sure that was all the usecases in the toolkit!

**Pull request merged**
