### PR TITLE
Add message for deleted for removed methods

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
Fixes an issue with versioning from #148 which was missed by the bot.

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check versioning

**Comment by IsakNaslundBh** [comment]
@BHoMBot this is a DevOps instruction. I am requesting a force check on: versioning

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required

**Review by MartinHenriksen — APPROVED** [review]

**Review by MartinHenriksen — APPROVED** [review]
That is correct! Thanks for fixing Isak

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance

**Review by FraserGreenroyd — APPROVED** [review]
Versioning file looks good and works, thanks @IsakNaslundBh @MartinHenriksen

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
