### PR TITLE
Add basic Read-Write functionality for Panels

### LINKED ISSUE #52: RFEM_Toolkit: Add support for panels
#### Description:
support functionality to read and write Panels in RFEM

### LINKED ISSUE #53: RFEM_Toolkit: Add support for basic surface properties
#### Description:
Add read and write functionality for basic surface properties

### LINKED ISSUE #61: RFEM_Toolkit: Remove Common_Engine reference
#### Broken rules:
All Spatial methods have been moved out of the Common_Engine and deprecated.
See https://github.com/BHoM/BHoM_Engine/issues/1624

#### Suggestions to restore compliance:
The Toolkit should switch to using Spatial_Engine instead.

And unless it's using a non-deprecated method from Common_Engine, the reference should be removed as well.

### PR DESCRIPTION
**Pull request by MartinHenriksen**
### Issues addressed by this PR

Closes #52 
Closes #53 
Closes #61 
 

 ### Test files

https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/RFEM_Toolkit/RFEM_Toolkit-ReadWritePanels.gh?csf=1&web=1&e=o5QppE

 ### Changelog

 ### Additional comments

as surface properties does not exist independently form a surface in RFEM (as sections do for bars) the usual adapter conventions could not be followed completely, i.e. you cannot create surface properties and then associate them with surfaces, properties can only be created with the surface it self!

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@MartinHenriksen How are things going with this PR? Do you have anyone in your office that is able to test this? If so, I can review the code.

**Comment by MartinHenriksen** [comment]
@IsakNaslundBh basic feature is there (a bit of cleaning still needed) and I have @arturtomczak lined up to test

**Comment by FraserGreenroyd** [comment]
> @IsakNaslundBh basic feature is there (a bit of cleaning still needed) and I have @arturtomczak lined up to test

@MartinHenriksen is there a rough timeline for the clean up and test? :smile:

**Comment by MartinHenriksen** [comment]
> @MartinHenriksen is there a rough timeline for the clean up and test? 😄
should be within a few hours

**Comment by MartinHenriksen** [comment]
> The standard slab properties are pushed properly.
> 
> The ribbed and waffle slab properties are not pushed correctly, it assigns the surface with the "Orthotropic" property, however within the orthotropic property it needs to be further assigned as a unidirectional ribbed plate (ribbed slab) or a bidirectional ribbed plate (waffle slab)

@staintono missed that one... should be fixed now. I have updated the test script

**Comment by FraserGreenroyd** [comment]
As discussed with @MartinHenriksen on a call, have resolved the conflicts and nothing more :smile:

**Pull request merged**
