### PR TITLE
Push and Pull of Parametric Sections and Beams

### LINKED ISSUE #160: Push and Pull of Parametric Sections and Beams
#### Description:
The Push of Parametric Cross Sections and Bars is not working as correctly.  
Some Sections, Typically I and Tee section are not getting through. Simultaniously the material has is not recongnized an connected to the section. 
When Pushing Beams either just some do get through while in other caseds all will have the same sections assigned. 

#### Steps to reproduce:

Place a series of Parametric sections and push them to RFEM.

### PR DESCRIPTION
**Pull request by Arne-Martensen**
### Issues addressed by this PR

During the pushing process of multiple beams with different cross-sections, they were mistakenly pushed as multiple beams with equal cross-sections. Furthermore, there were issues with correctly pushing beams that had a T-shaped section. Standard L-shaped beams could not be pushed at all.

 Closes #160 

 

 ### Test files

[Test File Bar Push/Pull](https://burohappold-my.sharepoint.com/:u:/r/personal/arne_martensen_burohappold_com/Documents/Documents/RFEM5/TestScripts/PushPullBars.gh?csf=1&web=1&e=C3Ukyk)
[Test File Section Push/Pull](https://burohappold-my.sharepoint.com/:u:/r/personal/arne_martensen_burohappold_com/Documents/Documents/RFEM5/TestScripts/PushPullSections_TestFile%20(1).gh?csf=1&web=1&e=EQXEhQ)
 ### Changelog

- Added A Customized Comparator to compare BHoM Sections
- Modified the reading writing of L-Sections

### CODE REVIEW

**Review by staintono — APPROVED** [review]
Cross Sections can be successfully pushed and pulled when using an empty RFEM model. This was tested by creating numerous bars with differing cross sections and pushing/pulling them in GH. The code was not reviewed.

**Comment by Arne-Martensen** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check versioning
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
