### PR TITLE
Read and Write for RigidLinks

### LINKED ISSUE #91: Cannot pull rigid links
#### Description:

Cannot pull a rigid link, gives the follow error:
```
1. This component failed to run properly.
- Error: No. must be greater than zero!
- Occured in  BH.Adapter.RFEM.RFEMAdapter.ReadBars(List`1 ids)
     called from BH.Adapter.RFEM.RFEMAdapter.IRead(Type type, IList ids, ActionConfig actionConfig)
- Are you sure you have the correct type of inputs? Check their description for more details.
```

#### Steps to reproduce:

image

#### Expected behaviour:

Allow rigid links to be pulled.

### LINKED ISSUE #112: Push RigidLinks
#### Description:

Add functionality to Push RigidLinks into RFEM model

### PR DESCRIPTION
**Pull request by MartinHenriksen**
### Issues addressed by this PR

 Closes #91 
Closes #112 

 

 ### Test files

[test file](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/RFEM_Toolkit/RFEM_Toolkit-ReadWriteRigidLinks.gh?csf=1&web=1&e=T4U6WB)

 ### Changelog

- RFEM Hinge-properties are not supported and will default to constraint = Fixed

### CODE REVIEW

**Comment by hmoubarak** [comment]
image

Creating Rigidlink with multiple secondary nodes is not supported. There should be a warning.

**Review by hmoubarak — APPROVED** [review]
LGTM

**Comment by hmoubarak** [comment]
@BHoMBot check copyright compliance

**Comment by hmoubarak** [comment]
@BHoMBot check installer

**Comment by hmoubarak** [comment]
@BHoMBot check installer

**Comment by MartinHenriksen** [comment]
@BHoMBot check installer

**Pull request merged**
